# Generated by Django 2.2.1 on 2019-06-01 06:49

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='UrlInput',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.URLField(max_length=1000)),
                ('shortenUrl', models.CharField(blank=True, max_length=1000, null=True)),
                ('noOfHit', models.PositiveIntegerField(default=0)),
            ],
        ),
    ]
