# Generated by Django 2.2.1 on 2019-06-01 12:43

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='urlinput',
            name='created_at',
            field=models.DateTimeField(blank=True, default=django.utils.timezone.now, null=True),
        ),
        migrations.AddField(
            model_name='urlinput',
            name='ip_address',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
