# Generated by Django 2.2.1 on 2019-06-02 04:39

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_auto_20190601_1243'),
    ]

    operations = [
        migrations.CreateModel(
            name='UrlDetails',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url_hit_at', models.DateTimeField(blank=True, default=django.utils.timezone.now, null=True)),
                ('ip_address', models.PositiveIntegerField(blank=True, null=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='urlinput',
            name='ip_address',
        ),
    ]
