# Generated by Django 2.2.1 on 2019-06-02 04:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_auto_20190602_0439'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='UrlDetails',
            new_name='UrlDetail',
        ),
    ]
