# Generated by Django 2.2.1 on 2019-06-02 07:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_auto_20190602_0440'),
    ]

    operations = [
        migrations.DeleteModel(
            name='UrlDetail',
        ),
    ]
