# Generated by Django 2.2.1 on 2019-06-03 07:29

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0005_delete_urldetail'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='urlinput',
            name='noOfHit',
        ),
        migrations.CreateModel(
            name='Stat',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url_hit_time', models.DateTimeField(blank=True, default=django.utils.timezone.now, null=True)),
                ('ip_address', models.PositiveIntegerField(blank=True, null=True)),
                ('urlinputdetails', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.UrlInput')),
            ],
        ),
    ]
