# Generated by Django 2.2.1 on 2019-06-03 09:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0006_auto_20190603_0729'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stat',
            name='ip_address',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
        migrations.AlterField(
            model_name='stat',
            name='urlinputdetails',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stats', to='home.UrlInput'),
        ),
    ]
