# Generated by Django 2.2.1 on 2019-06-03 11:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0008_auto_20190603_0954'),
    ]

    operations = [
        migrations.AddField(
            model_name='stat',
            name='country',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
