# Generated by Django 2.2.1 on 2019-06-05 01:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0009_stat_country'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stat',
            name='url_input_details',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stats', related_query_name='key', to='home.UrlInput'),
        ),
    ]
